name: recurrence_kit_example
description: Example app demonstrating the recurrence_kit package.
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  recurrence_kit:
    path: ../
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
